In [1]:
#import dependencies

import pandas as pd

import matplotlib.pyplot as plt

import numpy as np

import random

from citipy import citipy

import sys
sys.path.append("..")

from config import weather_api_key

from config import gkey

import time
from datetime import datetime

import requests

In [2]:
#create set of lat and long, combine w zip

lats = np.random.uniform(-90, 90, size = 2000)

lngs = np.random.uniform(-180, 180, size= 2000)

lat_lngs = zip(lats, lngs)

lat_lngs

In [3]:
coordinates = list(lat_lngs)

In [4]:
cities = []

for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name 

    if city not in cities:
        cities.append(city)

len(cities)

761

In [5]:
cities[:10]

['bluff',
 'carlos chagas',
 'tanete',
 'tuktoyaktuk',
 'busselton',
 'bathsheba',
 'jurado',
 'carnarvon',
 'tautira',
 'yellowknife']

In [6]:
url = (f"http://api.openweathermap.org/data/2.5/weather?units=Imperial&appid={weather_api_key}")

In [7]:
# test_url = url +"&q=San+Diego"

# sd = requests.get(test_url).json()

# sd.keys()

In [8]:
# city_test = []

# # city = cities[0]


# #loop through cities in our list
# for i, city in enumerate(cities):

#     #group cities in sets of 50 for logging (plus sleep60 to prevent timeout err)
#     if (i < 20):
#     #create endpoint url with each city (concat with replace fxn, repl space w plus)
#         city_url = url +"&q=" + city.replace(" ","+")


#     # Parse the JSON and retrieve data.
#         city_weather = requests.get(city_url).json()

# # # Parse out the needed data.
#         city_lat = city_weather["coord"]["lat"]
#         city_lng = city_weather["coord"]["lon"]
#         city_max_temp = city_weather["main"]["temp_max"]
#         city_humidity = city_weather["main"]["humidity"]
#         city_clouds = city_weather["clouds"]["all"]
#         city_wind = city_weather["wind"]["speed"]
#         city_country = city_weather["sys"]["country"]
#         description = city_weather["weather"][0]["description"]

#         #convert date to iso standard
#         city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S')

#         #append city info into city data list 
#         city_test.append({"City": city.title(),
#                                 "Country": city_country,
#                                 "Lat": city_lat,
#                                 "Lng": city_lng,
#                                 "Max Temp": city_max_temp,
#                                 "Description":description,
#                                 "Humidity": city_humidity,
#                                 "Cloudiness": city_clouds,
#                                 "Wind Speed": city_wind,
#                                 "Date": city_date})


# city_test

In [9]:
#Error: printed only "city not found". Issue with set/count or enumeration? 
# 
#  #empty list for weather data
# city_data = []

# #beginning of logging
# # print beginning of logging
# print("Beggining Data Retrieval        ")
# print("--------------------------------")

# #create counters
# record_count = 1
# set_count = 1

# #loop through cities in our list
# for i, city in enumerate(cities):

#     #group cities in sets of 50 for logging (plus sleep60 to prevent timeout err)
#     if (i % 50 == 0 and i >=50):
#         set_count +=1
#         record_count = 1
#         time.sleep(60)
    
#     #create endpoint url with each city (concat with replace fxn, repl space w plus)
#     city_url = url +"&q=" + city.replace(" ","+")

#     #log url, record, and set numbers/city
#     print(f"Processing record {record_count} of Set {set_count} | {city}")
#     #add 1 to record count
#     record_count +=1 

#     #run api requests for each city 
#     try:
#         # Parse the JSON and retrieve data.
#         city_weather = requests.get(city_url).json()

#         # Parse out the needed data.
#         city_lat = city_weather["coord"]["lat"]
#         city_lng = city_weather["coord"]["lng"]
#         city_max_temp = city_weather["main"]["temp_max"]
#         city_humidity = city_weather["main"]["humidity"]
#         city_clouds = city_weather["clouds"]["all"]
#         city_wind = city_weather["wind"]["speed"]
#         city_country = city_weather["sys"]["country"]
#         description = city_weather["weather"][0]["description"]

#         #convert date to iso standard
#         city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S')

#         #append city info into city data list 
#         city_data.append({"City": city.title(),
#                             "Country": city_country,
#                             "Lat": city_lat,
#                             "Lng": city_lng,
#                             "Max Temp": city_max_temp,
#                             "Description":description,
#                             "Humidity": city_humidity,
#                             "Cloudiness": city_clouds,
#                             "Wind Speed": city_wind,
#                             "Date": city_date})
#     except:
#         print("City not found. Skipping...")
#         pass

# #indate data load complete 
# print("--------------------------------")
# print("Data Retrieval Complete         ")
# print("--------------------------------")

In [10]:
#empty list for weather data 
city_data = []

# print beginning of logging
print("Beggining Data Retrieval        ")
print("--------------------------------")

#create counters
record_count = 1
set_count = 1

#loop through cities in our list
for i, city in enumerate(cities):

    #group cities in sets of 50 for logging (plus sleep60 to prevent timeout err)
    if (i % 50 == 0 and i >=50):
        set_count +=1
        record_count = 1
        time.sleep(60)
    
    #create endpoint url with each city (concat with replace fxn, repl space w plus)
    city_url = url +"&q=" + city.replace(" ","+")

    #log url, record, and set numbers/city
    print(f"Processing record {record_count} of Set {set_count} | {city}")
    #add 1 to record count
    record_count +=1 

#run api requests for each city 
    try:
        # Parse the JSON and retrieve data.
        city_weather = requests.get(city_url).json()

        # Parse out the needed data.
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        description = city_weather["weather"][0]["description"]

        # Convert the date to ISO standard.
        city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S')


        # Append the city information into city_data list. dict for each city where key value pairs are from weather parsed data 
        city_data.append({"City": city.title(),
                            "Lat": city_lat,
                            "Lng": city_lng,
                            "Max Temp": city_max_temp,
                            "Humidity": city_humidity,
                            "Cloudiness": city_clouds,
                            "Wind Speed": city_wind,
                            "Description":description,
                            "Country": city_country,
                            "Date": city_date})
    
    #in line w try 
    except:
        print ("City not found. Skipping...")
        pass

#Indicate Data Loading is complete (flush w margin)

print("--------------------------------")
print("Data Retrieval Complete         ")
print("--------------------------------")

Beggining Data Retrieval
--------------------------------
Processing record 1 of Set 1 | bluff
Processing record 2 of Set 1 | carlos chagas
Processing record 3 of Set 1 | tanete
Processing record 4 of Set 1 | tuktoyaktuk
Processing record 5 of Set 1 | busselton
Processing record 6 of Set 1 | bathsheba
Processing record 7 of Set 1 | jurado
Processing record 8 of Set 1 | carnarvon
Processing record 9 of Set 1 | tautira
Processing record 10 of Set 1 | yellowknife
Processing record 11 of Set 1 | ushuaia
Processing record 12 of Set 1 | kutum
Processing record 13 of Set 1 | loja
Processing record 14 of Set 1 | buraydah
Processing record 15 of Set 1 | nhamunda
Processing record 16 of Set 1 | novyy urengoy
Processing record 17 of Set 1 | albany
Processing record 18 of Set 1 | sivaki
Processing record 19 of Set 1 | airai
Processing record 20 of Set 1 | chuy
Processing record 21 of Set 1 | marsa matruh
Processing record 22 of Set 1 | avarua
Processing record 23 of Set 1 | grindavik
Processing record 24 of Set 1 | kolosovka
Processing record 25 of Set 1 | matagami
Processing record 26 of Set 1 | joppatowne
Processing record 27 of Set 1 | rikitea
Processing record 28 of Set 1 | tokur
Processing record 29 of Set 1 | atuona
Processing record 30 of Set 1 | broome
Processing record 31 of Set 1 | black river
Processing record 32 of Set 1 | khandyga
Processing record 33 of Set 1 | oum hadjer
Processing record 34 of Set 1 | provideniya
Processing record 35 of Set 1 | tual
Processing record 36 of Set 1 | semporna
Processing record 37 of Set 1 | mataura
Processing record 38 of Set 1 | saleaula
City not found. Skipping...
Processing record 39 of Set 1 | rawson
Processing record 40 of Set 1 | hobyo
Processing record 41 of Set 1 | butaritari
Processing record 42 of Set 1 | cabo san lucas
Processing record 43 of Set 1 | puerto ayora
Processing record 44 of Set 1 | vilhena
Processing record 45 of Set 1 | cidreira
Processing record 46 of Set 1 | mackenzie
Processing record 47 of Set 1 | hobart
Processing record 48 of Set 1 | eureka
Processing record 49 of Set 1 | klaksvik

In [ ]:
city_data_df = pd.DataFrame(city_data)

In [ ]:
city_data_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Description,Country,Date
0,Meulaboh,4.1363,96.1285,76.66,87,22,3.60,few clouds,ID,2022-03-28 21:38:51
1,Punta Arenas,-53.1500,-70.9167,44.71,87,75,9.22,shower rain,CL,2022-03-28 21:46:05
2,Pemberton,50.3164,-122.8027,53.29,97,96,2.21,overcast clouds,CA,2022-03-28 21:39:07
3,Hithadhoo,-0.6000,73.0833,81.16,65,58,6.22,broken clouds,MV,2022-03-28 21:39:08
4,Torbay,47.6666,-52.7314,43.57,83,75,10.36,broken clouds,CA,2022-03-28 21:46:06
...,...,...,...,...,...,...,...,...,...,...
691,Garden City,42.3256,-83.3310,32.88,38,40,13.80,scattered clouds,US,2022-03-28 22:05:28
692,Zhanaozen,43.3000,52.8000,29.98,56,28,11.86,scattered clouds,KZ,2022-03-28 22:06:28
693,Westport,41.1415,-73.3579,30.33,32,40,18.41,scattered clouds,US,2022-03-28 22:06:29
694,Puerto Ayacucho,5.6639,-67.6236,75.83,94,100,4.79,light rain,VE,2022-03-28 22:06:29
695,El Jicaro,14.9167,-89.9000,90.81,44,91,7.40,overcast clouds,GT,2022-03-28 22:06:30

In [ ]:
new_column_order = ["City", "Country", "Lat", "Lng", "Max Temp", "Humidity", "Cloudiness", "Wind Speed", "Description"]

city_data_clean_df = city_data_df[new_column_order]

city_data_clean_df

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Description
0,Meulaboh,ID,4.1363,96.1285,76.66,87,22,3.60,few clouds
1,Punta Arenas,CL,-53.1500,-70.9167,44.71,87,75,9.22,shower rain
2,Pemberton,CA,50.3164,-122.8027,53.29,97,96,2.21,overcast clouds
3,Hithadhoo,MV,-0.6000,73.0833,81.16,65,58,6.22,broken clouds
4,Torbay,CA,47.6666,-52.7314,43.57,83,75,10.36,broken clouds
...,...,...,...,...,...,...,...,...,...
691,Garden City,US,42.3256,-83.3310,32.88,38,40,13.80,scattered clouds
692,Zhanaozen,KZ,43.3000,52.8000,29.98,56,28,11.86,scattered clouds
693,Westport,US,41.1415,-73.3579,30.33,32,40,18.41,scattered clouds
694,Puerto Ayacucho,VE,5.6639,-67.6236,75.83,94,100,4.79,light rain
695,El Jicaro,GT,14.9167,-89.9000,90.81,44,91,7.40,overcast clouds

In [ ]:
output_data_file = "WeatherPy_Database.csv"

city_data_clean_df.to_csv(output_data_file, index_label="City ID")